activities/urls.py
from django.urls import path

from . import views

app_name = 'activities'

urlpatterns = [
    path('', views.my_activity, name='template_activity'),
]

feature_about/urls.py
from django.urls import path

from . import views

app_name = 'feature_about'

urlpatterns = [
    path('', views.about, name='about'),
]

feature_login/urls.py
from django.urls import path

from . import views

app_name = 'feature_login'

urlpatterns = [
    path('', views.signupPage, name='signup'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('gallery/', views.gallery, name='gallery'),
    path('courses/', views.courses, name='courses'),
    path('courses/<str:pk>/', views.detailCourse, name="detail_course"),
    path('update_course/<str:pk>/', views.updateCourse, name="update_course"),
    path('delete_course/<str:pk>/', views.deleteCourse, name="delete_course"),
]

myWebsite/urls.py
from django.contrib import admin
from django.urls import include, path
from activities.views import my_activity

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('webStory1', include('story1.urls')),
    path('my_activity/', include('activities.urls')),
    path('about/', include('feature_about.urls')),
    path('story8/', include('feature_story8.urls')),
    path('auth/', include('feature_login.urls')),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='webStory1'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <!--navbar-->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #FEF9CF">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarGallery" aria-controls="navbarGallery" 
      aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify" id="navbarGallery">
      <ul class="navbar-nav nav-item">
          <li><a class="nav-link" href="{% url 'main:home' %}" style="color: black;">HOME</a></li>
          <li><a class="nav-link" href="{% url 'main:gallery' %}" style="color: black;">GALLERY</a></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: black;">
              STORY
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'story1:webStory1' %}" style="color: black;">STORY 1</a>
              <a class="dropdown-item" href="{% url 'story8:story8' %}" style="color: black;">STORY 8</a>
            </div>
          </li> 
          <li><a class="nav-link" href="{% url 'main:courses' %}" style="color: black;">COURSES</a></li>
          <li><a class="nav-link" href="{% url 'activities:template_activity' %}" style="color: black;">ACTIVITIES</a></li>
          <li><a class="nav-link" href="{% url 'feature_about:about' %}" style="color: black;">ABOUT ME</a></li>
      </ul>
    </div>
    
    {% if user.is_authenticated %}
    <span style="margin-right: 25px;">Hello, {{request.user}}</span>
    <span style="margin-right: 25px;"><a href="{% url 'feature_login:logout' %}" style="color: black;">Logout</a></span>

    {% else %}
    <span style="margin-right: 25px;"><a href="{% url 'feature_login:signup' %}" style="color: black;">Sign Up</a></span>
    <span style="margin-right: 25px;"><a href="{% url 'feature_login:login' %}" style="color: black;">Login</a></span>

    {% endif %}
  </nav>

  {% block content %}
  {% endblock content %}

  <!--my contact--> 
  <div class="jumbotron jumbotron-fluid" style="background-color: #d4d0c2;">
    <div class="container" style="text-align: center;">
      <h1 class="display-4";>Contact Me</h1><br>
      <p class="lead"><a href="https://mail.google.com/mail/u/0/#inbox?compose=GTvVlcSBmmDLGQKZSfWvZkzmrPBkPrPTfgtFpKDslldNBtwntLfzQQJFNQQJnnwcCJCbzXJKdMcxL" 
        target="-blank" style="color: black;">faizahs0212@gmail.com</a></p>
      <p class="lead"><a href="https://www.instagram.com/faizah.fai/?hl=id" target="-blank" style="color: black;">faizah.fai</a></p>
    </div>
  </div>
</body>
</html>