main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('gallery/', views.gallery, name='gallery'),
    path('courses/', views.courses, name='courses'),
    path('courses/<str:pk>/', views.detailCourse, name="detail_course"),
    path('update_course/<str:pk>/', views.updateCourse, name="update_course"),
    path('delete_course/<str:pk>/', views.deleteCourse, name="delete_course"),
]

myWebsite/urls.py
from django.contrib import admin
from django.urls import include, path
from activities.views import my_activity

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('webStory1', include('story1.urls')),
    path('my_activity/', include('activities.urls')),
    path('about/', include('feature_about.urls')),
    path('story8/', include('feature_story8.urls')),
    path('auth/', include('feature_login.urls')),
]

main/models.py
from django.db import models

class Course(models.Model):
    course = models.CharField(max_length=100, default="")
    lecturer = models.CharField(max_length=100, default="")
    credit = models.CharField(max_length=10, default="")
    description = models.CharField(max_length=400, default="")
    termnyear = models.CharField(max_length=50, default="", verbose_name="Term and Year")
    room = models.CharField(max_length=20, default="")

    def __str__(self):
        return self.course + self.lecturer + self.credit + self.description + self.termnyear + self.room

main/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class CourseForm(forms.ModelForm):
    course = forms.CharField(widget = forms.TextInput(attrs={'placeholder':'Add course'}))
    lecturer = forms.CharField(widget = forms.TextInput(attrs={'placeholder':'Add lecturer'}))
    credit = forms.CharField(widget = forms.TextInput(attrs={'placeholder':'Example: 3'}))
    description = forms.CharField(widget = forms.TextInput(attrs={'placeholder':'Add description to this course'}))
    termnyear = forms.CharField(widget = forms.TextInput(attrs={'placeholder':'Example: GASAL 2019/2020'}), label="Term and Year")
    room = forms.CharField(widget = forms.TextInput(attrs={'placeholder':'Add the classroom'}))

    class Meta:
        model = Course
        fields = '__all__'

main/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request, 'main/home.html')

def gallery(request):
    return render(request, 'main/gallery.html')

@login_required(login_url='feature_login:login')
def courses(request):
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/courses')
    
    courses = Course.objects.all()
    form = CourseForm()

    context = {'courses':courses, 'form':form}
    return render(request, 'main/courses.html', context)

def updateCourse(request, pk):
    course = Course.objects.get(id=pk)
    form = CourseForm(instance=course)

    if request.method == 'POST':
        form = CourseForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            return redirect('/courses')

    context = {'form':form}
    return render(request, 'main/update_course.html', context)

def deleteCourse(request, pk):
    item = Course.objects.get(id=pk)

    if request.method == 'POST':
        item.delete()
        return redirect('/courses')

    context = {'item':item}
    return render(request, 'main/delete_course.html', context)

def detailCourse(request, pk):
    item = Course.objects.get(id=pk)
    context = {'item':item}
    return render(request, 'main/detail_course.html', context)

main/templates/main/courses.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Courses</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/coursesstyle.css' %}">
{% endblock meta %}

{% block content %}
    <br><br><br>

    <div class="center-column">
        <form method="POST" action="/courses/">
            {% csrf_token %}
            {{form}}
            <input class="btn btn-info submit" type="submit" name="Add Course">
        </form>

        {% for course in courses %}
            <div class="item-row">
                <a href="{% url 'main:detail_course' course.id %}"><p>{{course.course}}</p></a>
                <a class="btn btn-sm btn-info submit" href="{% url 'main:update_course' course.id %}">Update</a>
                <a class="btn btn-sm btn-danger" href="{% url 'main:delete_course' course.id %}">Delete</a>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

main/templates/main/delete_course.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Delete Course</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/coursesstyle.css' %}">
{% endblock meta %}

{% block content %}  
    <br><br><br>

    <div class="center-column" style="height: 200px;">
        <div class="text-center">
            <p>Delete "{{item.course}}"?</p>
            <a class="btn btn-danger" style="width: 100px;" href="{% url 'main:courses' %}">Cancel</a>

            <form method="POST", action="">
                {% csrf_token%}
                <input class="btn btn-info submit" style="width: 100px;" type="submit"  value="Confirm">
            </form>
        </div>
    </div>
{% endblock content %}

main/templates/main/detail_course.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Detail of Courses</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/coursesstyle.css' %}">
{% endblock meta %}

{% block content %}
    <br><br><br>

    <div class="center-column" style="height: auto;">
        <p>{{item.course}}</p>
        <p>{{item.termnyear}}</p>
        <p>Lecturer: {{item.lecturer}}</p>
        <p>{{item.credit}} SKS</p>
        <p>{{item.description}}</p>
        <p>In {{item.room}} room</p>
    </div>
{% endblock content %}

main/templates/main/gallery.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Gallery</title>
{% endblock meta %}

{% block content %}
<!--gallery text-->
    <br><br><br>   
    <div class="text-center">
        <img src="{% static 'img/gallery.png' %}" class="img-fluid" alt="GalleryText"><br><br>
    </div>

    <!--photos-->
    <div class="container text-center">
        <div class="row">
            <div class="col">
                <img src="{% static 'img/quote.jpg' %}" class="img-fluid" alt="Quote">
                <img src="{% static 'img/mirror.jpg' %}" class="img-fluid" alt="Mirror" width="400px" height="400px">
                <img src="{% static 'img/april.jpg' %}" class="img-fluid" alt="April">
                <img src="{% static 'img/friends.jpg' %}" class="img-fluid" alt="Friend">
                <img src="{% static 'img/jellyfish.jpg' %}" class="img-fluid" alt="Jellyfish">
                <img src="{% static 'img/puzzle.jpg' %}" class="img-fluid" alt="Puzzle">
            </div>
        </div>
    </div><br><br>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Homepage</title>
{% endblock meta %}

{% block content %}
  <!--name and photo-->
  <br><br><br>
  <div class="text-center">
    <img src="{% static 'img/hello.png' %}" class="img-fluid" alt="Hello">
    <br>
    <img src="{% static 'img/myname.png' %}" class="img-fluid" alt="My Name">
    <br>
    <img src="{% static 'img/myphoto.png' %}" class="img-fluid" alt="My Photo">
  </div>

  <!--aboout me-->
  <div class="jumbotron jumbotron-fluid" style="background-color: #ffecb7;">
    <div class="container">
      <h1 class="display-4";">About Me</h1>
      <hr class="my-4">
      <p class="lead">I live in Central Jakarta since I was born. Now, I am a second year 
        student of Information System in University of Indonesia. And I am learning about Front End Developer in my college.
        Hope you enjoy this website.
      </p>
    </div>
  </div>

  <!--educational background-->
  <div class="jumbotron jumbotron-fluid" style="background-color: #ffc982;">
    <div class="container" style="text-align: right;">
      <h1 class="display-4">Educational Background</h1>
      <hr class="my-4">
      <p class="lead">12 Benhil Elementary School</p>
      <p class="lead">12 Islamic Junior High School</p>
      <p class="lead">70 Senior High School</p>
    </div>
  </div>

  <!--experience-->
  <div class="jumbotron jumbotron-fluid" style="background-color: #ff9b6d;">
    <div class="container">
      <h1 class="display-4";>Experience</h1>
      <hr class="my-4">
      <p class="lead" style="font-weight: 400;">70 Senior High School</p>
      <ul style="display: inline;">PIC of Wall Magazine of ROHIS 70</ul>
      <ul>Documentation Staff of Setara</ul>
      <p class="lead" style="font-weight: 400;">University of Indonesia</style></p>
      <ul style="display: inline;">MDC FUKI Staff</ul>
      <ul>Equipment Staff of SIWAK-NG</ul>
    </div>
  </div>
{% endblock content %}

main/templates/main/update_course.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Update Course</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/coursesstyle.css' %}">
{% endblock meta %}

{% block content %}
    <br><br><br>

    <div class="center-column" style="height: 800px;">
        <h3>Update Course</h3>
        <form method="POST", action="">
            {% csrf_token %}

            {{form}}
            <input class="btn btn-info submit" type="submit" name="Update Course">
        </form>
    </div>
{% endblock content %}